message:
  file:
    path: ''
  language: 'chinese'

residence:
  file:
    path: ''
  # 需要同时修改 Residence 的领地数量
  amount:
    # 权限是 residencestoragespigot.amount.player 允许玩家最多拥有 5 个领地
    player: 5
    # 权限是 residencestoragespigot.amount.member 允许玩家最多拥有 10 个领地。
    member: 10